export const lessonContent = `CREATE TABLE IF NOT EXISTS lesson_content (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id INT NOT NULL,
    content_title TEXT NULL,
    content_position INT DEFAULT 100,
    content TEXT NOT NULL,
    content_type VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("lesson_id") REFERENCES "course_lesson" ("id")
);`;
