export const courses = `CREATE TABLE IF NOT EXISTS courses (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    description TEXT,
    thumbnail VARCHAR,
    content TEXT,
    category_ids INT[],
    author_id INT NOT NULL,
    status INT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("author_id") REFERENCES "users" ("id"),
    FOREIGN KEY ("status") REFERENCES "course_status" ("id")
);`;
