export const posts = `CREATE TABLE IF NOT EXISTS posts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    content VARCHAR NOT NULL,
    content_type VARCHAR DEFAULT 'text',
    owner_id INT NOT NULL,
    group_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY ("owner_id") REFERENCES "users" ("id"),
    FOREIGN KEY ("group_id") REFERENCES "groups" ("id")
);`;
