export const courseLesson = `CREATE TABLE IF NOT EXISTS course_lesson (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    course_id INT NOT NULL,
    lesson_summary TEXT NOT NULL,
    lesson_no INT NOT NULL,
    lesson_title VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("course_id") REFERENCES "courses" ("id")
);`;
