export const groups = `CREATE TABLE IF NOT EXISTS groups(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INT NOT NULL,
    name VARCHAR NOT NULL,
    status VARCHAR DEFAULT "active",
    type VARCHAR DEFAULT "public",
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY ("course_id") REFERENCES "courses" ("id"),
    FOREIGN KEY ("owner_id") REFERENCES "users" ("id")
);`;
