export const groups = `CREATE TABLE IF NOT EXISTS groups (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    owner_id INT NOT NULL,
    name VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'active',
    type VARCHAR DEFAULT 'public',
    description VARCHAR,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("owner_id") REFERENCES "users" ("id")
);`;
