export const groups = `CREATE TABLE IF NOT EXISTS groups(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id INT NOT NULL,
    name VARCHAR NOT NULL,
    course_id INT,
    status VARCHAR DEFAULT 'active',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
`;
