export const assignments = `CREATE TABLE IF NOT EXISTS assignments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL,
    description TEXT NOT NULL,
    deadline VARCHAR NOT NULL,
    assignment_quiz TEXT NOT NULL,
    assignment_answers VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);`;
