export const courses = `CREATE TABLE IF NOT EXISTS courses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description TEXT,
    thumbnail VARCHAR,
    summary TEXT,
    category_ids INT[],
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);`